apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: guestbook-civo
  namespace: argocd
spec: 
  destination: 
    #namespace: guestbook-civo
    #server: "https://212.2.243.159:6443"
  #project: default
  source: 
    path: guest2
    repoURL: "git@github.com:shfy70/test.git"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
